### ISSUE TITLE
[Request] Firefox / UserScript version

### ISSUE THREAD

**Issue by FallenStar08** [MrFusiion/MapGenieProUnlock#1]
Hey, would it be possible to get a firefox compatible version? I was able to get 3.0 working on firefox by changing the manifest a bit but no luck with 4.0 and I don't know enough about extensions to fix it.

Thanks a lot, appreciate your work on this extension.

**Comment by MrFusiion** [comment]
I'll give it a try.

**Comment by MrFusiion** [comment]
firefox support is now added under the "firefox" branch for now.

**Comment by MrFusiion** [comment]
Firefox support will be added on the main branch in the next few days. And I will add a tutorial how to sign and build the extension to install firefox.
