### ISSUE TITLE
Direct link to mark doesn't work

### ISSUE THREAD

**Issue by Doliman100** [MrFusiion/MapGenieProUnlock#4]
### Expected behavior
Loading the script doesn't affect selection of marks. They may become translucent if found, but don't hide.

### Actual behavior
The mark hides after script loaded.

### Steps to reproduce the behavior
1. open link to mark, for example https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=176096
2. now you see the mark
3. but after the console message "Map hijacker loaded", the mark disappears

**Comment by MrFusiion** [comment]
Should now be fixed in v4.20
