### ISSUE TITLE
Plugin is deleted after browser restart.

### ISSUE THREAD

**Issue by Elc3r** [MrFusiion/MapGenieProUnlock#6]
The plug-in works great except that it deletes itself after restarting the browser. After re-adding it works great and the saved data is reloaded. The problem is that it repeats over and over again.

![image](https://user-images.githubusercontent.com/76127715/179486454-cf318326-9e11-425e-adcc-e0e02177b9f4.png)

![image](https://user-images.githubusercontent.com/76127715/179487906-befcc9d7-5e19-4de0-9a95-fb0f92d0c83f.png)

**Comment by MrFusiion** [comment]
couldn't reproduce the issue, but v3.4.0 should now load the extension settings correctly. Try it out and let me know if the problem is solved.

**Comment by Elc3r** [comment]
Thanks, problem solved. Plugin remains after browser restarts.
