### ISSUE TITLE
remember selected categories?

### ISSUE THREAD

**Issue by kevindevm** [MrFusiion/MapGenieProUnlock#9]
can you add to remembember with categories have selected? cuz if i reload the browser will foget and select all

**Comment by MrFusiion** [comment]
remember categories should already work with version 4.3.0 on chrome and firefox. Which version do you have and on which browser you running the extension? And if its possible can you give a screenshot from the extension error log.

**Comment by kevindevm** [comment]
browser chrome v 103.0.5060.134  x64
extension v2.3.0

idk what you by error log.. where can i find that?
here is a video https://youtu.be/id_3Snp3_p0

**Comment by MrFusiion** [comment]
To find the error log type this in the url bar "chrome://extensions/", And then click on the red button "Errors" if it is not there there are no errors.

And to be sure did you enable the checkbox all the way on the left.
![image](https://user-images.githubusercontent.com/71613276/182144366-75cf64c9-97b6-4869-99c4-a69279d55493.png)

**Comment by MrFusiion** [comment]
Normally you need pro for that feature but the extension unlocks it.

**Comment by kevindevm** [comment]
my bad did not see that checkbox.. it does work

**Comment by MrFusiion** [comment]
Well, it's well hidden, especially on big maps with lots of categories. So I can't blame you. I may add a setting to the popup that also enables that feature so it's easier to find.
